baseurl = "/"
disablePathToLower =  true
languageCode = "ja-JP"
title = "FONOのサイト"
cannonifyurls = true
paginate = 4 
theme = "hugo-dusk"
hasCJKLanguage = true

[author]
    name = "ふぉの"

SectionPagesManu = "main"
pygmentStyle = "vim"
pygmentCodeFences = true

[[menu.main]]
    name = "Posts"
    weight = -120
    identifier = "post"
    url = "/post/"

[[menu.main]]
    name = "Tags"
    weight = -110
    identifier = "tag"
    url = "/tags/"

[params.meta]
    keywords = "blog, tech, てくろぐ, 趣味"
    description = "雑記"

[params]
    github = "fono09"
    twitter = "fono0c"
    email = "fono(at)fono.jp"
    mastodon = "https://ma.fono.jp/@fono"
    theme_colors = "default-dark"
    mainSections = ["post"]
