baseurl = "/"
disablePathToLower =  true
languageCode = "ja-JP"
title = "FONOのサイト"
cannonifyurls = true
paginate = 3
theme = "hugo-dusk"

[author]
    name = ""

SectionPagesManu = "main"
pygmentStyle = "native"
pygmentCodeFences = true

[[menu.main]]
    name = "Posts"
    weight = -120
    identifier = "post"
    url = "/post/"

[[menu.main]]
    name = "Tags"
    weight = -110
    identifier = "tag"
    url = "/tags/"

[params.meta]
    keywords = "blog, tech, てくろぐ, 趣味"
    description = "雑記"

[params]
    github = "fono09"
    twitter = "fono0c"
    email = "fono(at)fono.jp"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color


