baseurl = "https://fono.jp/"
disablePathToLower =  true
languageCode = "ja-JP"
title = "FONOのサイト"
theme = "hugo-dusk"

[author]
    name = ""

SectionPagesManu = "main"

[[menu.main]]
    name = "Posts"
    weight = -120
    identifier = "post"
    url = "/post/"

[[menu.main]]
    name = "Tags"
    weight = -110
    identifier = "tag"
    url = "/tags/"

[params.meta]
    keywords = "blog, tech, てくろぐ, 趣味"
    description = "雑記"

[params]
    github = "fono09"
    twitter = "fono09"
    email = "fono(at)fono.jp"




